// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrD_OVwUDN88X3GFLLN9PQEs9MdSy924I',
    appId: '1:54071717180:web:8caec4b4d25ad025728239',
    messagingSenderId: '54071717180',
    projectId: 'skateshopdb',
    authDomain: 'skateshopdb.firebaseapp.com',
    storageBucket: 'skateshopdb.firebasestorage.app',
    measurementId: 'G-ESNQH3CDQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSb_cpmanE_SqRImIh0tQ_QsgYyaSCSVs',
    appId: '1:54071717180:android:37c454691fcce049728239',
    messagingSenderId: '54071717180',
    projectId: 'skateshopdb',
    storageBucket: 'skateshopdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_CnMkwpt415qWCee-Q8y4wZuWHUD46I',
    appId: '1:54071717180:ios:a8eb013428cbc679728239',
    messagingSenderId: '54071717180',
    projectId: 'skateshopdb',
    storageBucket: 'skateshopdb.firebasestorage.app',
    iosBundleId: 'com.skateshop.skateshopApp',
  );
}
